# Generated by Django 3.0.2 on 2020-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='number_of_task',
            field=models.IntegerField(),
        ),
    ]
