# Generated by Django 3.0.2 on 2020-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdz', '0002_auto_20200115_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(default='', upload_to='image_solution'),
        ),
    ]
