# Generated by Django 3.0.2 on 2020-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdz', '0003_auto_20200115_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_solution'),
        ),
    ]
