# Generated by Django 3.0.2 on 2020-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdz', '0004_auto_20200115_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.TextField(),
        ),
    ]
